language: go
go:
  - "1.10.x"
matrix:
  include:
    os:
      - linux
      - osx
    before_install:
      - sudo apt-get update 
      - sudo apt install libudev-dev
      - sudo apt install libusb-1.0-0-dev
      - go get github.com/skycoin/hardware-wallet-go
      - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.10.2
    script:
      - golangci-lint run --no-config  --deadline=3m --concurrency=2 --skip-dirs=device-wallet/usb -E goimports -E golint -E varcheck -E unparam -E deadcode -E structcheck ./...
      - go test github.com/skycoin/hardware-wallet-go/device-wallet/
