language: go
go:
  - "1.10.x"
matrix:
  include:
    - os: linux
env:
  - PROTOC_VERSION=3.6.1 PROTOC_ZIP="protoc-$PROTOC_VERSION-$TRAVIS_OS_NAME-x86_64.zip"
before_install:
  - sudo apt-get update
  - sudo apt install libudev-dev libusb-1.0-0-dev
  - curl -OL https://github.com/google/protobuf/releases/download/$PROTOC_VERSION/$PROTOC_ZIP
  - sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
  - rm -f $PROTOC_ZIP
  - git clone --branch v1.2.0 --depth 1 https://github.com/gogo/protobuf $GOPATH/src/github.com/gogo/protobuf
  - ( cd $GOPATH/src/github.com/gogo/protobuf/protoc-gen-gogo && go install )
install:
  - make proto
  - go get github.com/skycoin/hardware-wallet-go
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.10.2
script:
  - make check
  - make test
notifications:
  # https://github.com/kvld/travisci-telegram TravisCI Telegram Bot integration
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

