language: go
go:
  - "1.10.x"
matrix:
  include:
    - os: linux
    - os: osx
before_install:
  - source ./ci-scripts/install-$TRAVIS_OS_NAME.sh
  - git submodule update --remote --recursive
  - sh "./device-wallet/messages/ci-scripts/install-$TRAVIS_OS_NAME.sh"
  - sh "./device-wallet/messages/ci-scripts/common.sh"
install:
  - make vendor_proto
  - go get github.com/skycoin/hardware-wallet-go
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.10.2
script:
  - make check
  - make test
notifications:
  # https://github.com/kvld/travisci-telegram TravisCI Telegram Bot integration
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

